### ISSUE TITLE
Help with Child Theme

### ISSUE THREAD

**Issue by onespaceman** [giansi/gravstrap-theme#1]
I need help setting up a child theme that inherits gravstrap. I'm following [this guide](https://getgrav.org/blog/theme-development-with-inheritance)

When add mytheme.php it throws the error

> Whoops \ Exception \ ErrorException (E_ERROR)
> Class 'Grav\Theme\Gravstrap' not found

files:

mytheme/
--- css/
--- --- custom.css
--- blueprints.yaml
--- mytheme.yaml
--- mytheme.php

custom.css:

```
* {
  background: #FF0000;
}
```

mytheme.yaml

```
enabled: true
streams:
 schemes:
   theme:
     type: ReadOnlyStream
     prefixes:
       '':
         - user/themes/mytheme
         - user/themes/gravstrap-theme
```

mytheme.php

```
<?php
namespace Grav\Theme;

use Grav\Common\Theme;

class Mytheme extends Gravstrap
{
}
```
