### ISSUE TITLE
Extending gravstrap-theme

### ISSUE THREAD

**Issue by mediaclinic** [giansi/gravstrap-theme#4]
I'm trying to extend theme to customize it, but Grav gives me error:

`syntax error, unexpected '-', expecting '{'`

Might be something to do with the hyphen. My code here:

`class MyThemeName extends Gravstrap-Theme
{
}`

**Comment by giansi** [comment]
Hi,
you must not extend GravstrapTheme but Theme class:

```
use Grav\Common\Theme;

class MyThemeName extends Theme {}
```

though that's not mandatory, while you must add the follwing code to mytheme.yaml:

```
streams:
   schemes:
     theme:
       type: ReadOnlyStream
       prefixes:
         '':
         - user/themes/mytheme
         - user/themes/gravstraptheme
```

You will find more information about theme inheritance here: https://getgrav.org/blog/theme-development-with-inheritance
